### ISSUE TITLE
Missing credits.

### ISSUE THREAD

**Issue by Sanduhr32** [duncte123/How2Bot#1]
https://github.com/duncte123/DuncteBot/blob/b1e7b88ffb3789f3fbb4e6d573a6587d232914cc/src/ml/duncte123/dunctebot/DuncteBot.java#L81-L94

Since this is official Skybot code from you i want credits!

https://github.com/duncte123/SkyBot/blob/6adedb7129fd824abd1984a90aee4caac2c8977e/src/main/java/ml/duncte123/skybot/utils/GuildUtils.java#L189-L200

**Comment by duncte123** [comment]
I have to credit my own code from my own repo?
